class SessionsController < ApplicationController
  #this action is called when the browser navigates to GET localhost:3000/login (see routes.rb for the route)
  #this action calls the new.html.erb view that generates the login form with two fields and a 'login' button
  def new
  end

  #this action is called when the browser navigates to POST localhost:3000/login
  #this happens when the 'login' button is pressed in the login form generated by the new view
  def create
    user = User.find_by(name: params[:name])
    if user and user.authenticate(params[:password])
      #set the session key called 'user_id' to the id of the user object (user.id)
      #this will store the database id of the user in the client browser
      ##### ENTER CODE HERE######

      redirect_to admin_url
    else
      redirect_to login_url, alert: "Invalid user/password combination"
    end

  end

  def destroy
    #set the session key "user_id" to nil
    ##### ENTER CODE HERE######
  end
end
